#!/usr/bin/env node
/**
 * Renders the reference models to STL with OpenSCAD.
 *
 *   node models/build.mjs
 *
 * These are the "this is roughly what you were aiming at" models shown in a
 * checkpoint panel once someone has submitted or finished it. They are
 * deliberately plain: a reference, not a solution to copy dimension for
 * dimension. The .scad sources live beside this file so they can be edited.
 *
 * Swapping any one of these for a photo of a real club part later is a single
 * file change in src/content/path.ts.
 */

import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

// fileURLToPath, not hand-rolling it: this path contains a space, which stays
// percent-encoded in a URL pathname and then fails every fs call.
const HERE = path.dirname(fileURLToPath(import.meta.url));
const OUT = path.join(HERE, '..', 'public', 'assets', 'reference');

const CANDIDATES = [
  'C:/Program Files/OpenSCAD/openscad.com',
  'C:/Program Files/OpenSCAD/openscad.exe',
  '/usr/bin/openscad',
  'openscad',
];

const openscad = CANDIDATES.find((p) => p === 'openscad' || fs.existsSync(p));
if (!openscad) {
  console.error('OpenSCAD not found. Install it, or add its path to CANDIDATES.');
  process.exit(1);
}

fs.mkdirSync(OUT, { recursive: true });

const sources = fs
  .readdirSync(HERE)
  .filter((f) => f.endsWith('.scad'))
  .sort();

/**
 * OpenSCAD 2021 only writes ASCII STL, which stores every coordinate as a
 * decimal string and runs about five times the size it needs to. This rewrites
 * the same triangles as binary STL, which the viewer also parses faster.
 */
function toBinaryStl(asciiPath) {
  const text = fs.readFileSync(asciiPath, 'utf8');
  const NUM = /-?\d+(?:\.\d+)?(?:[eE][-+]?\d+)?/g;

  const tris = [];
  for (const block of text.split(/facet\s+normal/).slice(1)) {
    const v = block.match(NUM);
    if (!v || v.length < 12) continue;
    tris.push(v.slice(0, 12).map(Number));
  }

  const buf = Buffer.alloc(84 + tris.length * 50);
  buf.write('binary STL, generated by models/build.mjs', 0, 'ascii');
  buf.writeUInt32LE(tris.length, 80);

  let off = 84;
  for (const t of tris) {
    for (const n of t) {
      buf.writeFloatLE(n, off);
      off += 4;
    }
    buf.writeUInt16LE(0, off);
    off += 2;
  }

  fs.writeFileSync(asciiPath, buf);
  return tris.length;
}

let total = 0;
for (const src of sources) {
  const stl = path.join(OUT, src.replace(/\.scad$/, '.stl'));
  execFileSync(openscad, ['-o', stl, path.join(HERE, src)], { stdio: 'pipe' });

  const before = fs.statSync(stl).size / 1024;
  const tris = toBinaryStl(stl);
  const after = fs.statSync(stl).size / 1024;
  total += after;

  console.log(
    '  ' +
      src.replace('.scad', '').padEnd(22) +
      String(tris).padStart(6) +
      ' tris   ' +
      before.toFixed(0).padStart(4) +
      'KB ascii -> ' +
      after.toFixed(0).padStart(3) +
      'KB binary',
  );
}

console.log('\n' + sources.length + ' models, ' + total.toFixed(0) + 'KB total');
